server:
  port: 8080
  host: localhost
db:
  port: 5432
  host: localhost
  name: your_name
  username: your_username
  password: your_password
jwt:
  secret: somesecrethere
email:
  host: smtp.somehost.io
  port: 25
  username: someusername
  password: somepassword
  from: someemail@gmail.com
